### ISSUE TITLE
.Net Nano Framework 有可能移植到 rt-thread 吗？

### ISSUE THREAD

**Issue by maikebing** [RT-Thread-packages/FreeRTOS-Wrapper#23]
地址是
https://github.com/nanoframework/nf-interpreter
他有运行在FreeRTOS   的 编译方法。 地址是
 https://github.com/nanoframework/nf-interpreter/tree/main/targets/FreeRTOS

**Comment by mysterywolf** [comment]
这个仓库只负责对FreeRTOS本身的兼容，至于FreeRTOS下游衍生出来的一些东西的兼容可行性，本仓库不予以评估。

**Comment by mysterywolf** [comment]
如果想要兼容的话，建议可以向上游直接提交rt-thread移植代码，就像你列举的FreeRTOS文件夹一样。
